CREATE TABLE MEMBERINFO
(
	ID 			NVARCHAR(50) PRIMARY KEY,
    `PASSWORD`	NVARCHAR(300),
    `NAME`		NVARCHAR(30)
);

CREATE TABLE AUTHORITY
(
	AUTHORITY 			NVARCHAR(50) PRIMARY KEY,
    AUTHORITY_NAME		NVARCHAR(50) 
);

CREATE TABLE MEMBER_AUTHORITY
(
	ID 			NVARCHAR(50),
    AUTHORITY	NVARCHAR(50) 
);

CREATE TABLE `GROUPS`
(
	ID 			INTEGER,
    GROUP_NAME	NVARCHAR(50) 
);

CREATE TABLE GROUPS_MEMBER
(
	GROUP_ID INTEGER,
    MEMBER_ID NVARCHAR(50)
);

CREATE TABLE GROUPS_AUTHORITY
(
	GROUP_ID 	INTEGER,
    AUTHORITY 	NVARCHAR(50)
);

CREATE TABLE SECURED_RESOURCE
(
	RESOURCE_ID			NVARCHAR(10),
    RESOURCE_NAME		NVARCHAR(50),
    RESOURCE_PATTERN 	NVARCHAR(100),
    RESOURCE_TYPE		NVARCHAR(10),
    SORT_ORDER 			INTEGER
);

CREATE TABLE SECURED_RESOURCE_AUTHORITY
(
	RESOURCE_ID	NVARCHAR(10),
    AUTHORITY 	NVARCHAR(50),
    `NAME` 		NVARCHAR(50)
);


CREATE TABLE ROLE
(
	ROLE_ID 	NVARCHAR(2),
    ROLE_NAME	NVARCHAR(100) 
);

CREATE TABLE MEMBER_ROLE
(
	ID 			NVARCHAR(50),
    ROLE_ID 	NVARCHAR(2)
)

